version: '3.8'

services:
  db-test:
    image: postgres:15-alpine
    container_name: novamind-db-test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=novamind_test
    ports:
      - "15432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - novamind-test-network

  pgadmin-test:
    image: dpage/pgadmin4:latest
    container_name: novamind-pgadmin-test
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@novamind.test
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "15050:5050"
    depends_on:
      - db-test
    volumes:
      - pgadmin_test_data:/var/lib/pgadmin
    networks:
      - novamind-test-network

  redis-test:
    image: redis:alpine
    container_name: novamind-redis-test
    ports:
      - "16379:6379"
    volumes:
      - redis_test_data:/data
    networks:
      - novamind-test-network

volumes:
  postgres_test_data:
  pgadmin_test_data:
  redis_test_data:

networks:
  novamind-test-network:
    driver: bridge