version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app/backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/novamind
      - LOG_LEVEL=INFO
      - ENVIRONMENT=development
    depends_on:
      - db
      - redis
    networks:
      - novamind-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=novamind
    ports:
      - "5432:5432"
    networks:
      - novamind-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - novamind-network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  novamind-network:

volumes:
  postgres_data:
  redis_data:
