name: Standalone Tests

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'backend/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  standalone-tests:
    name: Run standalone tests
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install -r requirements-test.txt
        pip install pytest-cov

    - name: Make script executable
      run: chmod +x run-standalone-tests.sh

    - name: Run standalone tests
      run: |
        ./run-standalone-tests.sh
      
    - name: Generate coverage report
      run: |
        python -m pytest app/tests/standalone/ --cov=app --cov-report=xml --cov-report=html

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: |
          backend/htmlcov
          backend/coverage.xml

    - name: Check coverage thresholds
      run: |
        COVERAGE=$(python -c "import xml.etree.ElementTree as ET; tree = ET.parse('coverage.xml'); root = tree.getroot(); print(root.attrib['line-rate'])")
        COVERAGE_PERCENT=$(python -c "print(round(float('${COVERAGE}') * 100, 2))")
        echo "Coverage: ${COVERAGE_PERCENT}%"
        
        if (( $(echo "${COVERAGE_PERCENT} < 80" | bc -l) )); then
          echo "::warning::Coverage ${COVERAGE_PERCENT}% is below the 80% threshold"
        fi

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: backend/test-results/standalone-results.xml